version: '3'

services:
  openvpn:
    image: castone38/dockervpn:latest
    container_name: openvpn
    restart: unless-stopped
    ports:
      - "${OPENVPNPORT}:${OPENVPNPORT}/udp"
    volumes:
      - /srv/cloudAtHome/openvpn/data:/etc/openvpn
    cap_add:
      - NET_ADMIN

  caddy:
    image: castone38/docker-caddy:latest
    container_name: caddy
    restart: unless-stopped
    depends_on:
      openvpn:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      - /srv/cloudAtHome/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /srv/cloudAtHome/caddy/data:/data
      - /srv/cloudAtHome/caddy/config:/config
    cap_add:
      - NET_ADMIN

  ghost-db:
    image: mariadb:latest
    container_name: ghost-db
    volumes:
      - /srv/cloudAtHome/ghost-db/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MARIADB_ROOT_PASSWORD=${DBROOTPASSW}
    restart: unless-stopped
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "--password=${DBROOTPASSW}", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  ghost:
    image: ghost:5-alpine
    container_name: ghost
    depends_on:
      caddy:
        condition: service_started
      ghost-db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "2368"
    environment:
      - NODE_ENV=production
      - url=${MYURL}
      - mail__transport=SMTP
      - mail__options__host=${MAILHOST}
      - mail__options__port=${MAILPORT}
      - mail__options__auth__user=${MAILUSER}
      - mail__options__auth__pass=${MAILPASSW}
      - mail__from=${MAILFROM}
      - database__client=mysql
      - database__connection__host=ghost-db
      - database__connection__user=root
      - database__connection__password=${DBROOTPASSW}
      - database__connection__database=ghost
    volumes:
      - /srv/cloudAtHome/ghost/data:/var/lib/ghost/content
