version: '3.1'

volumes:
  wordpress-db:

services:
  openvpn:
    image: castone38/dockervpn:latest
    container_name: openvpn
    restart: unless-stopped
    ports:
      - "${OPENVPNPORT}:1194/udp"
    volumes:
      - /srv/cloudAtHome/openvpn/data:/etc/openvpn
    cap_add:
      - NET_ADMIN

  caddy:
    image: castone38/docker-caddy:latest
    container_name: caddy
    restart: unless-stopped
    depends_on:
      openvpn:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/cloudAtHome/wordpress/data:/var/www/html:ro
      - /srv/cloudAtHome/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /srv/cloudAtHome/caddy/data:/data
      - /srv/cloudAtHome/caddy/config:/config
    cap_add:
      - NET_ADMIN

  wordpress-db:
    image: mariadb:latest
    container_name: wordpressdb
    volumes:
      - wordpress-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${DBROOTPASSW}
      MYSQL_ROOT_PASSWORD: ${DBROOTPASSW}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "--password=${DBROOTPASSW}", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  wordpress:
    image: wordpress:fpm-alpine
    container_name: wordpress
    depends_on:
      caddy:
        condition: service_started
      wordpress-db:
        condition: service_healthy
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: wordpressdb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${DBROOTPASSW}
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - /srv/cloudAtHome/wordpress/data:/var/www/html
