version: '3'

volumes:
  nextcloud:
  nextcloud-db:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed

services:
  openvpn:
    image: castone38/dockervpn-client
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z
      - /srv/cloudAtHome/openvpn/data:/vpn

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/cloudAtHome/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /srv/cloudAtHome/caddy/data:/data
      - /srv/cloudAtHome/caddy/config:/config

  nextcloud:
    image: castone38/nextcloud-all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
      - /var/run/docker.sock:/var/run/docker.sock:ro 
    ports:
      - 8080:8080
    environment: 
      - APACHE_PORT=11000
